name: CI | Unit

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "**"

jobs:
  ci-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup node cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm ci

      - name: Lint scripts
        run: npm run lint

      - name: Run tests
        run: npm run test
