name: Release nightly channel

defaults:
  run:
    shell: bash

on:
  workflow_run:
    workflows: ["CI | Nightly"]
    branches: [develop]
    types:
      - completed
  workflow_dispatch:

jobs:
  release-nightly:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required by Akeyless
      contents: read
      packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v5
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN",
              "/WebComponents/prod/tokens/PROGRESS_NPM_REGISTRY_TOKEN": "NPM_TOKEN"
            }
          export-secrets-to-environment: false

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Setup git
        run: |
          git config user.name "kendo-bot"
          git config user.email "kendouiteam@progress.com"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup node cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm ci

      - name: Publish
        run: npx semantic-release --nightly
        env:
          GITHUB_TOKEN: ${{ steps.import-secrets.outputs.GH_TOKEN }}
          NPM_TOKEN: ${{ steps.import-secrets.outputs.NPM_TOKEN }}
